- name: connecting to the host
  hosts: mongodb
   become: yes
  tasks: 
  - name: pinging the node
    ansible.builtin.ping:

   - name: Install Nginx
      package:
        name: nginx
        state: installed