- name: connecting to the host
  hosts: mongodb
  become: yes
  tasks: 
  - name: pinging the node
    ansible.builtin.ping:

  - name: ensure nginx is at the latest version
    apt:
      name: nginx
      state: latest
  - name: start nginx
    service: 
      name: nginx
      state: started
      enabled: yes