- name: This is an example to prompt the variables
  hosts: localhost
  vars_prompt: 
    - name: this_is_ to_prompt_the_name
      prompt: Enter your name
      private: false

    - name: This_is_to_enter_the_password_of_course
      prompt: Enter the course password
  tasks: 
  - name: printing the variables in the prompt
    ansible.builtin.debug:
      msg: "{{this_is_ to_prompt_the_name}}{{This_is_to_enter_the_password_of_course}}"