- name: This is an example to prompt the variables
  hosts: localhost
  vars_prompt: 
    - name: this_is_to_prompt_the_name  #this is the variable name 
      prompt: Enter your name
      private: false

    - name: This_is_to_enter_the_password_of_course
      prompt: Enter the course password
  tasks: 
  - name: printing the variables in the prompt
    ansible.builtin.debug:
      msg: "username:{{this_is_to_prompt_the_name}},password:{{This_is_to_enter_the_password_of_course}}"