- name: This is to access the variables from the inventory file
  hosts: localhost
  tasks:
  - name: printing the variables from inventory
    ansible.built.debug:
      msg: "my fullname is {{full_name}}, course is {{course}},duration is {{duration}}"