- name: This is to access the variables from the inventory file
  hosts: mongodb
  tasks:
  - name: printing the variables from inventory
    ansible.builtin.debug:
      msg: "username:{{mongodb_username}}, mondodb is is {{MONGO_DB}}"