- name: example of the variable inheritance
  hosts: localhost
  vars:
    full_name: sai kiran reddy
    course: DevOps
    duration: 3 months
  tasks:
  - name: printing the values
    ansible.builtin.debug:
      msg: "my fullname is {{full_name}}, course is {{course}},duration is {{duration}}"
  - name: overriding the values
    vars:
      full_name: saikiran reddy sudhireddy
      job: Devops engineer
    ansible.builtin.debug:
      msg: "my fullname is {{full_name}}, job is {{job}},duration is {{duration}}"