- name: Checking if the roboshop user exists 
  hosts: localhost
  tasks:
  - name: executing the id roboshop command 
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: yes
  - name : printing the exit status
    ansible.builtin.debug:
    msg: "{{output}}"

