- name: this file is to practice the advanced loop
  hosts: mongodb
  become: yes
  tasks: 
  - name: printing the advanced loop elements
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop: 
    - { name: 'nginx', state: 'installed' }
    - { name: 'nginx', state: 'started' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'cyrus-sasl-plain', state: 'installed' }
    - { name: 'mailx', state: 'absent'}
