- name: Create Directory if Not Exists
  hosts: localhost
  vars_prompt:
  - name: directory_path
    prompt: please enter the path of directory
    private: false
  tasks: 
  - name: Check if the directory exists
    ansible.builtin.stat:
      path: "{{ directory_path }}"
      register: dir_check
      ignore_errors: true

  - name: printing the output
    ansible.builtin.debug:
      msg: "{{dir_check}}"