- name: This is the example to create an user dynamically
  hosts: localhost
  vars_prompt:
- name: name_of_user
  prompt: please enter the user to create
  private: false
  tasks:
  - name: checking the user
    ansible.builtin.command: id {{name_of_user}}
    register: output
    ignore_errors: true


  - name: Creating the user
    become: yes
    ansible.builtin.user:
      name: "{{ name_of_user }}"
      state: present    
    when: output.rc != 0